### ISSUE TITLE
Re-Export `useLazyQuery`

### ISSUE THREAD

**Issue by garritfra** [appmotion/apollo-augmented-hooks#13]
When a project uses `useLazyQuery`, it currently has to import it from `@apollo/client`. Does it make sense to re-export it from `apollo-augmented-hooks` to avoid multiple import statements?

**Comment by mindnektar** [comment]
Sure! You up for providing a PR? :)

**Comment by garritfra** [comment]
Will do!

**Comment by mindnektar** [comment]
Thanks! I've released v2.2.0 with your changes.
