### ISSUE TITLE
How to extract loading and error states from mutation?

### ISSUE THREAD

**Issue by dryhurst** [appmotion/apollo-augmented-hooks#4]
i withdraw the issue.

**Comment by dryhurst** [comment]
so i was thinking about this some more today. i am just so used to thinking of the useMutation tupal pattern `const [ mutatorFunction, {loading, error} ] = useMutation(MY_MUTATION)` that i couldn't get my head around how i would capture loading or error states otherwise. but this will work. this post is really me more thinking out loud than anything, but if you're trying to lure people away from the apollo/client implementation to yours perhaps just amending the documentation slightly. otherwise exposing loading and error states from the mutation would make transitioning to this implementation a lot easier 

```
setIsSaving(true) // a piece of react state i can pass to props
try {
  const result = await mutation({input: { prop1: 'val1', prop2: 'val2' }}) // the mutation
} catch (error) {
  console.error(error);
}
setIsSaving(false)
```

**Comment by mindnektar** [comment]
Fair enough! Still, I've taken your feedback to heart and will mull it over some. Thank you!

**Comment by adavis** [comment]
Is there an example for this? I have the same question. We use  something like this `const [mutation, { error, loading }] =
    useLoginWithThirdPartyServiceMutation();
` all over our project currently. I'd love to migrate to using this package instead without having to change too much code. Thanks!

**Comment by garritfra** [comment]
@adavis This library is a drop-in replacement for `@apollo/client`. The hooks have the same signature as the original ones, with some additional fields. 🙂

**Comment by garritfra** [comment]
@adavis sorry about my half-baked reply. You're right, there is a difference.

Try this:

```js
// "Use" the mutation in your component
const loginWithThirdPartyService = useLoginWithThirdPartyServiceMutation();

// Call the mutation where needed
const { data } = await loginWithThirdPartyService();
```

Notice that just the mutation function is returned from `useMutation`, instead of a tuple.

**Comment by mindnektar** [comment]
Hey @adavis - I'm currently sick, so unfortunately I can't help you right away, but I've been regretting my decision not to return the tuple for a while now. When I'm back on my feet, I'll likely release a major version update introducing the breaking change of returning the tuple. I'm glad you're interested in this library and I hope you're willing to wait a bit longer. :)

**Comment by adavis** [comment]
> Hey @adavis - I'm currently sick, so unfortunately I can't help you right away, but I've been regretting my decision not to return the tuple for a while now. When I'm back on my feet, I'll likely release a major version update introducing the breaking change of returning the tuple. I'm glad you're interested in this library and I hope you're willing to wait a bit longer. :)

I hope you feel better soon! And I'm happy to wait, I think this will be great for our app. Take care.
