### ISSUE TITLE
Modify object before saving to cache?

### ISSUE THREAD

**Issue by iankberry** [appmotion/apollo-augmented-hooks#5]
First of all, thanks for the great library! I'm impressed how well thought out it is at such an early stage.

I'm struggling to do something that I have previously used `cache.writeFragment()` for. Basically, I have a mutation that returns an object to save to the cache **except** for a specific property that I would like to override locally before saving to the cache. Basically some additional local state the server is unaware of. Using every method I have tried reading the docs, the originally unaltered mutation response is being saved to the cache, even though the `fields` modifier is correctly adding it to the list (the `events` query).

Here is an example that works as expected:
```ts
mutation({
    variables: {
        someField: 'value'
    },
    update: (cache, result) => {
        const { data: { createEvent } } = result;
        cache.writeFragment({
            id: cache.identify(createEvent),
            fragment: EventFragment,
            data: {
                ...createEvent,
                score: 10
            },
        });
    },
    modifiers: [{
        fields: {
            events: ({ includeIf }) => includeIf(true)
        }
    }],
});
```

Here is an example that does not work, where the `score` saved to the cache has the value from the API, not the value specified here. Perhaps I am not understanding how `cacheObject` is supposed to be used?

```ts
mutation({
    variables: {
        someField: 'value'
    },
    modifiers: [{
        cacheObject: item => {
            return {
                ...item,
                score: 10,
            }
        },
        fields: {
            events: ({ includeIf }) => includeIf(true)
        }
    }],
});
```

Thanks in advance for your help!

**Comment by mindnektar** [comment]
Hi, and thank you very much for your kind words. :)

`cacheObject` serves a single purpose: to determine which object in the cache is supposed to be modified. This means that `item` and `{ ...item, score: 10 }` are essentially the same thing in your example, because internally, only the object's `id` and `__typename` will be read and any other properties will be ignored.

To solve your problem, you'll simply need to add a second modifier:

```
modifiers: [{
    fields: {
        events: ({ includeIf }) => includeIf(true)
    }
}, {
    cacheObject: (item) => item,
    fields: {
        score: () => 10,
    }
}],
```

The first modifier adds the event to the root query's `events` list, and the second modifier changes the event's `score` field to 10. Hope that helps!

**Comment by iankberry** [comment]
Ah, thank you that did the trick! I tried adding the second modifier at one point but I omitted the `cacheObject` which made the difference. Thanks again for your help. I'll start working on migrating my gross cache code over to this library soon :-)

**Comment by mindnektar** [comment]
No problem! My cache modification code used to be gross as hell, too. Felt great when it finally became maintainable. :)
